### ISSUE TITLE
No build available to download.

### ISSUE THREAD

**Issue by xanderoot** [chunky-dev/chunky-opencl#1]
"Download the latest build and extract it." You show a jar file but there is none.

**Comment by Peregrine05** [comment]
The latest build is now at https://github.com/chunky-dev/chunky-opencl/actions/runs/10483408776

**Comment by KakashoLin** [comment]
It appears the file is expired?

**Comment by leMaik** [comment]
@KakashoLin You can now downloaded the .jar of the latest build from the releases page: https://github.com/chunky-dev/chunky-opencl/releases
